import type { Metadata } from 'next'
import './globals.css'

import Script from 'next/script'
import { Header } from '@/components/Header'
import { AppProvider } from '@/provider/queryProvider'
import { ToastProvider } from '@/provider/toastProvider'

export const metadata: Metadata = {
  title: 'Homework App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-TJVPMZP5"
            height="0"
            width="0"
            style={{ display: 'none', visibility: 'hidden' }}
          ></iframe>
        </noscript>
        <AppProvider>
          <ToastProvider>
            <div className="wrapper">
              <Header />
              <main>{children}</main>
            </div>
          </ToastProvider>
        </AppProvider>
      </body>
    </html>
  )
}
