import type { Metadata } from 'next'
import './globals.css'

import { Header } from '@/components/Header'
import { AppProvider } from '@/provider/queryProvider'

export const metadata: Metadata = {
  title: 'Homework App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <AppProvider>
          <div className="wrapper">
            <Header />
            <main>{children}</main>
          </div>
        </AppProvider>
      </body>
    </html>
  )
}
