import type Metadata from 'next'
// import { Inter } from 'next/font/google'
import './globals.css'

import { AppProvider } from '@/provider/queryProvider'
import { useCookie } from '@/hooks/useSetCookie'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { getCsrfToken } = useCookie()

  return (
    <html lang="ja">
      <body>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  )
}
